#!/bin/bash

docker-compose -f ./web1/docker-compose.yaml up -d
docker-compose -f ./web2/docker-compose.yaml up -d
docker-compose -f ./web3/docker-compose.yaml up -d
docker-compose -f ./web4/docker-compose.yaml up -d

