version: '3'

services:
  web1:
    # A container that exposes an API to show its IP address
    image: traefik/whoami
    labels:
      - "traefik.http.routers.web1.rule=Host(`web1.localhost`)"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true
